using System;
using System.Collections.Generic;

#nullable disable

// this file was auto-generated by the Scaffold-DbContext command line tool

namespace TextEmAllChallenge.Entities
{
    public partial class OfficeAssignment
    {
        public int InstructorId { get; set; }
        public string Location { get; set; }
        public byte[] Timestamp { get; set; }

        public virtual Person Instructor { get; set; }
    }
}
