using System;
using System.Collections.Generic;

#nullable disable

// this file was auto-generated by the Scaffold-DbContext command line tool

namespace TextEmAllChallenge.Entities
{
    public partial class OnlineCourse
    {
        public int CourseId { get; set; }
        public string Url { get; set; }

        public virtual Course Course { get; set; }
    }
}
