using System;
using System.Collections.Generic;

#nullable disable

// this file was auto-generated by the Scaffold-DbContext command line tool

namespace TextEmAllChallenge.Entities
{
    public partial class OnsiteCourse
    {
        public int CourseId { get; set; }
        public string Location { get; set; }
        public string Days { get; set; }
        public TimeSpan Time { get; set; }

        public virtual Course Course { get; set; }
    }
}
